# Generated by Django 4.0.3 on 2022-03-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_birthday_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
