# Generated by Django 4.0.3 on 2022-03-03 02:44

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='contacts.contact')),
            ],
        ),
    ]


    # operations = [
    #     migrations.RemoveField(
    #         model_name='note',
    #         name='creator',
    #     ),
    #     migrations.RemoveField(
    #         model_name='note',
    #         name='note',
    #     ),
    #     migrations.AddField(
    #         model_name='note',
    #         name='contact',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact'),
    #     ),
    #     migrations.AddField(
    #         model_name='note',
    #         name='text',
    #         field=models.CharField(blank=True, max_length=255, null=True),
    #     ),
    # ]






    # operations = [
    #     migrations.AlterField(
    #         model_name='note',
    #         name='creator',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
    #         name='Note',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('note', models.CharField(max_length=500)),
    #             ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
    #             ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='contacts.contact')),
    #         ],
    #     # ),
    #     migrations.RemoveField(
    #         model_name='contact',
    #         name='note',
    #     ),
    # ]
