# Generated by Django 4.0.3 on 2022-03-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_note_remove_contact_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='note',
            name='creator',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
