# Generated by Django 4.0.3 on 2022-03-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text_field',
            field=models.CharField(max_length=300),
        ),
    ]
