# Generated by Django 4.0.3 on 2022-03-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_note_creator_alter_note_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text_field',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
